config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root :to=>"home#index"
  resources :producao_cientificas

  resources :titulacoes

  resources :professores

end

app/models/producao_cientifica.rb
class ProducaoCientifica < ActiveRecord::Base
	has_and_belongs_to_many :professores
end

app/models/professor.rb
class Professor < ActiveRecord::Base
	has_and_belongs_to_many :titulacoes
	has_and_belongs_to_many :producao_cientificas
end

app/models/titulacao.rb
class Titulacao < ActiveRecord::Base
	has_and_belongs_to_many :professores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
  end
end

app/controllers/producao_cientificas_controller.rb
class ProducaoCientificasController < InheritedResources::Base
	def build_resource_params
    	[params.fetch(:producao_cientifica, {}).permit(:artigo,:monografia)]
    end
end

app/controllers/professores_controller.rb
class ProfessoresController < InheritedResources::Base
	def build_resource_params
    	[params.fetch(:professor, {}).permit(:nome,:cpf,:telefone,:endereco)]
    end
end

app/controllers/titulacoes_controller.rb
class TitulacoesController < InheritedResources::Base
	def build_resource_params
    	[params.fetch(:titulacao, {}).permit(:mestre,:pos,:doutor)]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/producao_cientificas_helper.rb
module ProducaoCientificasHelper
end

app/helpers/professores_helper.rb
module ProfessoresHelper
end

app/helpers/titulacoes_helper.rb
module TitulacoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ensino</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/producao_cientificas/_form.html.haml
= form_for @producao_cientifica do |f|
  - if @producao_cientifica.errors.any?
    #error_explanation
      %h2= "#{pluralize(@producao_cientifica.errors.count, "error")} prohibited this producao_cientifica from being saved:"
      %ul
        - @producao_cientifica.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :artigo
    = f.text_field :artigo
  .field
    = f.label :monografia
    = f.text_field :monografia
  .actions
    = f.submit 'Salvar'

app/views/producao_cientificas/edit.html.haml
%h1 Editing producao_cientifica

= render 'form'

= link_to 'Show', @producao_cientifica
\|
= link_to 'Back', producao_cientificas_path

app/views/producao_cientificas/index.html.haml
%h1 Lista Producao Cientifica

%table
  %tr
    %th Artigo
    %th Monografia
    %th
    %th
    %th

  - @producao_cientificas.each do |producao_cientifica|
    %tr
      %td= producao_cientifica.artigo
      %td= producao_cientifica.monografia
      %td= link_to 'Mostrar', producao_cientifica
      %td= link_to 'Editar', edit_producao_cientifica_path(producao_cientifica)
      %td= link_to 'Excluir', producao_cientifica, :method => :delete, :data => { :confirm => 'Tem certeza?' }

%br

= link_to 'Nova Producao cientifica', new_producao_cientifica_path

app/views/producao_cientificas/new.html.haml
%h1 Nova producao_cientifica

= render 'form'

= link_to 'Back', producao_cientificas_path

app/views/producao_cientificas/show.html.haml
%p#notice= notice

%p
  %b Artigo:
  = @producao_cientifica.artigo
%p
  %b Monografia:
  = @producao_cientifica.monografia

= link_to 'Edit', edit_producao_cientifica_path(@producao_cientifica)
\|
= link_to 'Back', producao_cientificas_path

app/views/professores/_form.html.haml
= form_for @professor do |f|
  - if @professor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@professor.errors.count, "error")} nao pode salvar, corrija os erros:"
      %ul
        - @professor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :cpf
    = f.number_field :cpf
  .field
    = f.label :telefone
    = f.number_field :telefone
  .field
    = f.label :endereco
    = f.text_field :endereco
  .actions
    = f.submit 'Salvar'

app/views/professores/edit.html.haml
%h1 Editar professor

= render 'form'

= link_to 'Show', @professor
\|
= link_to 'Back', professores_path

app/views/professores/index.html.haml
%h1 Lista de professores

%table
  %tr
    %th Nome
    %th Cpf
    %th Telefone
    %th Endereco
    %th
    %th
    %th

  - @professores.each do |professor|
    %tr
      %td= professor.nome
      %td= professor.cpf
      %td= professor.telefone
      %td= professor.endereco
      %td= link_to 'Mostrar', professor
      %td= link_to 'Editar', edit_professor_path(professor)
      %td= link_to 'Excluir', professor, :method => :delete, :data => { :confirm => 'Tem certeza?' }

%br

= link_to 'Novo Professor', new_professor_path

app/views/professores/new.html.haml
%h1 Novo professor

= render 'form'

= link_to 'Back', professores_path

app/views/professores/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @professor.nome
%p
  %b Cpf:
  = @professor.cpf
%p
  %b Telefone:
  = @professor.telefone
%p
  %b Endereco:
  = @professor.endereco

= link_to 'Editar', edit_professor_path(@professor)
\|
= link_to 'voltar', professores_path

app/views/titulacoes/_form.html.haml
= form_for @titulacao do |f|
  - if @titulacao.errors.any?
    #error_explanation
      %h2= "#{pluralize(@titulacao.errors.count, "error")} nao pode salvar, corrija os erros"
      %ul
        - @titulacao.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :mestre
    = f.text_field :mestre
  .field
    = f.label :pos
    = f.text_field :pos
  .field
    = f.label :doutor
    = f.text_field :doutor
  .actions
    = f.submit 'Salvar'

app/views/titulacoes/edit.html.haml
%h1 Editar titulacao

= render 'form'

= link_to 'Show', @titulacao
\|
= link_to 'Back', titulacoes_path

app/views/titulacoes/index.html.haml
%h1 Lista de titulacoes

%table
  %tr
    %th Mestre
    %th Pos
    %th Doutor
    %th
    %th
    %th

  - @titulacoes.each do |titulacao|
    %tr
      %td= titulacao.mestre
      %td= titulacao.pos
      %td= titulacao.doutor
      %td= link_to 'Mostrar', titulacao
      %td= link_to 'Editar', edit_titulacao_path(titulacao)
      %td= link_to 'Excluir', titulacao, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Nova Titulacao', new_titulacao_path

app/views/titulacoes/new.html.haml
%h1 Nova titulaçao

= render 'form'

= link_to 'Back', titulacoes_path

app/views/titulacoes/show.html.haml
%p#notice= notice

%p
  %b Mestre:
  = @titulacao.mestre
%p
  %b Pos:
  = @titulacao.pos
%p
  %b Doutor:
  = @titulacao.doutor

= link_to 'Editar', edit_titulacao_path(@titulacao)
\|
= link_to 'Voltar', titulacoes_path